<%@ Page Title="" Language="C#" MasterPageFile="~/admin/AdminMaster.master" AutoEventWireup="true" CodeFile="Users.aspx.cs" Inherits="admin_Users" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="body" Runat="Server">
    <form runat="server">

        <asp:SqlDataSource ID="UsersData" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
            SelectCommand="SELECT * FROM [Users]"
            DeleteCommand="DELETE FROM [Users] WHERE [username]=@username"
            UpdateCommand="UPDATE [Users] SET [isAdmin]=@isAdmin WHERE [username]=@username">
        <DeleteParameters>
            <asp:ControlParameter ControlID="GridView1" Name="username" PropertyName="SelectedDataKey" />
        </DeleteParameters>
           <DeleteParameters>
            <asp:ControlParameter ControlID="GridView1" Name="isAdmin" PropertyName="SelectedDataKey" />
        </DeleteParameters>
        </asp:SqlDataSource>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="username" DataSourceID="UsersData" 
            OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True">
            <Columns>
                <asp:BoundField DataField="username" HeaderText="username" ReadOnly="True" SortExpression="username" />
                <asp:CheckBoxField DataField="isAdmin" HeaderText="isAdmin" SortExpression="isAdmin" ReadOnly="false" />
            </Columns>
        </asp:GridView>

    </form>
</asp:Content>

